// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/coffee-story/CoffeeStory.tsx": () => import("../components/CoffeeStory/CoffeeStory.tsx")
};
